server:
  port: 8010

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:15432/kairos
#    url: jdbc:postgresql://db:5432/kairos // docker服务使用
    username: kairos
    password: kairos
  jpa:
    hibernate:
      ddl-auto: update  # 开发用，生产改 validate
    show-sql: true
    generate-ddl: false
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.kairos: DEBUG

# JWT
jwt:
  secret-key: ${JWT_SECRET:a2Fpcm9zX2Rldl91c2VyX3Bhc3N3b3JkXzEyMzQ1Njc4OQ==} # base64 {"kairos_dev_user_password_123456789"}
  expiration: 86400000  #24 小时